version: "3.9"

services:
  api:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=challege_api
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - PORT=3000
      - TOKEN_EXPIRY_HOURS=24
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: challege_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

volumes:
  postgres_data_prod:
