version: "3.9"

secrets:
  db_password:
    external: true   # la crea el workflow de deploy en la VM

networks:
  challenge_net:
    driver: overlay

volumes:
  postgres_data:

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: challenge_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - challenge_net
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  api:
    image: ghcr.io/eduardoTrigo/academia2025-challenge:prod
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "production"
      PORT: "3000"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_NAME: "challenge_api" 
      DB_USER: "postgres"
      TOKEN_EXPIRY_HOURS: "24"
    secrets:
      - db_password
    command: >
      sh -c "export DB_PASSWORD=$(cat /run/secrets/db_password) && node dist/app.js"
    networks:
      - challenge_net
    depends_on:
      - db
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 5s
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 2m
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.10"
          memory: 128M
