# Archivo .github/workflows/build.yml
name: build-and-push
on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
permissions:
  contents: read
  packages: write
env:
  # Definir el nombre de repositorio correcto y válido para Docker
  DOCKER_REPO_NAME: eduardotrigo/academia2025-challenge
jobs:
  docker:
    runs-on: ubuntu-24.04
    steps:
      # ... (resto de los pasos)
      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.DOCKER_REPO_NAME }}
          # ... (resto del metadata)
      # ... (resto de los pasos)
