name: build-and-push

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]

permissions:
  contents: read
  packages: write

env:
  DOCKER_REPO_NAME: eduardotrigo/academia2025-challenge

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image (prod)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: development
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ env.DOCKER_REPO_NAME }}:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max
