name: deploy-to-swarm

on:
  workflow_run:
    workflows: ["build-and-push"] 
    types:
      - completed 

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Retag latest build to .prod
        run: |
          docker pull ghcr.io/eduardotrigo/academia2025-challenge:dev
          docker tag ghcr.io/eduardotrigo/academia2025-challenge:dev ghcr.io/eduardotrigo/academia2025-challenge:prod
          docker push ghcr.io/eduardotrigo/academia2025-challenge:prod

      - name: Deploy to Swarm via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST_PINGGY }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT_PINGGY }}
          script: |
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker stack deploy -c /home/deploy/docker-stack.yml app_stack --with-registry-auth

