name: deploy-to-swarm

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Deploy to Swarm via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -x   # Esto imprime cada comando mientras se ejecuta
            DOCKER_REPO_NAME="eduardotrigo/academia2025-challenge"
            echo "🔐 Login en GHCR"
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            echo "⬇️ Descargando imagen dev"
            docker pull ghcr.io/$DOCKER_REPO_NAME:dev
            echo "🏷 Retag a prod"
            docker tag ghcr.io/$DOCKER_REPO_NAME:dev ghcr.io/$DOCKER_REPO_NAME:prod
            echo "🚀 Deploy con Swarm"
            docker stack deploy -c /home/deploy/docker-stack.yml app_stack --with-registry-auth
